import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/****************************************************************************
 Program Name: Stocks4UsGUI.java
 Programmer's Name: Kyrenia Ailen Andrade Avila
 Program Description: GUI application created for CIS355A Week 4 Lab, in which
 we can add and remove stocks to a Stocks list, and we get the Profit or Loss.
 ****************************************************************************/
public class Stocks4UsGUI extends javax.swing.JFrame 
{
    //class level references or attributes
    private DefaultListModel<Stock> model;

    /**
     * Creates new form Stocks4UsGUI
     */
    public Stocks4UsGUI() 
    {
        //create the model for the JList
        //needs to be created before the initComponents() so it can use it when reaching the JList
        model = new DefaultListModel<Stock>();
        
        initComponents();
        
        //set form to center the screen
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpMainTabs = new javax.swing.JTabbedPane();
        pnlStockList = new javax.swing.JPanel();
        scrStocks = new javax.swing.JScrollPane();
        lstStocks = new javax.swing.JList<>();
        lblProfitLoss = new javax.swing.JLabel();
        btnRemoveStock = new javax.swing.JButton();
        pnlAddStock = new javax.swing.JPanel();
        lblStockName = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblPurchasePrice = new javax.swing.JLabel();
        lblCurrentPrice = new javax.swing.JLabel();
        txtStockName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtPurchasePrice = new javax.swing.JTextField();
        txtCurrentPrice = new javax.swing.JTextField();
        btnAddStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Portfolio Management");

        jtpMainTabs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pnlStockList.setToolTipText("");

        lstStocks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstStocks.setModel(model);
        lstStocks.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstStocksValueChanged(evt);
            }
        });
        scrStocks.setViewportView(lstStocks);

        lblProfitLoss.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProfitLoss.setText("Profit / Loss");

        btnRemoveStock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoveStock.setText("Remove Stock");
        btnRemoveStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStockListLayout = new javax.swing.GroupLayout(pnlStockList);
        pnlStockList.setLayout(pnlStockListLayout);
        pnlStockListLayout.setHorizontalGroup(
            pnlStockListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrStocks)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStockListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStockListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProfitLoss, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlStockListLayout.createSequentialGroup()
                        .addGap(0, 173, Short.MAX_VALUE)
                        .addComponent(btnRemoveStock)))
                .addGap(181, 181, 181))
        );
        pnlStockListLayout.setVerticalGroup(
            pnlStockListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStockListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrStocks, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblProfitLoss)
                .addGap(18, 18, 18)
                .addComponent(btnRemoveStock)
                .addGap(24, 24, 24))
        );

        jtpMainTabs.addTab("List", pnlStockList);

        lblStockName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStockName.setText("Stock Name:");

        lblQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuantity.setText("Quantity:");

        lblPurchasePrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPurchasePrice.setText("Purchase Price:");

        lblCurrentPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurrentPrice.setText("Current Price:");

        txtStockName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPurchasePrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtCurrentPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnAddStock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddStock.setText("Add Stock");
        btnAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddStockLayout = new javax.swing.GroupLayout(pnlAddStock);
        pnlAddStock.setLayout(pnlAddStockLayout);
        pnlAddStockLayout.setHorizontalGroup(
            pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddStockLayout.createSequentialGroup()
                        .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStockName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStockName)
                            .addComponent(txtQuantity)))
                    .addGroup(pnlAddStockLayout.createSequentialGroup()
                        .addComponent(lblPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtPurchasePrice))
                    .addGroup(pnlAddStockLayout.createSequentialGroup()
                        .addComponent(lblCurrentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtCurrentPrice)))
                .addContainerGap())
            .addGroup(pnlAddStockLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(btnAddStock)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        pnlAddStockLayout.setVerticalGroup(
            pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddStockLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStockName)
                    .addComponent(txtStockName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPurchasePrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentPrice)
                    .addComponent(txtCurrentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnAddStock)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jtpMainTabs.addTab("Add Stock", pnlAddStock);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpMainTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpMainTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStockActionPerformed
        //verify thst the field are complete
        if (txtStockName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Stock name is required.", "Error. Missing Information", JOptionPane.ERROR_MESSAGE);
            txtStockName.requestFocus();
            return;     //ends the method
        }
        
        if (txtQuantity.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Quantity is required.", "Error. Missing Information", JOptionPane.ERROR_MESSAGE);
            txtQuantity.requestFocus();
            return;     //ends the method
        }
        
        if (txtPurchasePrice.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Purchase price is required.", "Error. Missing Information", JOptionPane.ERROR_MESSAGE);
            txtPurchasePrice.requestFocus();
            return;     //ends the method
        }
        
        if (txtCurrentPrice.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Current price is required.", "Error. Missing Information", JOptionPane.ERROR_MESSAGE);
            txtCurrentPrice.requestFocus();
            return;     //ends the method
        }
        
        //get input and validate data type
        String stockName = txtStockName.getText();
        
        double quantity = 0.0;
        try {
            quantity = Double.parseDouble(txtQuantity.getText());
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Invalid input for Quantity. Please use numbers only.", "Error. Invalid Data.", JOptionPane.ERROR_MESSAGE);
            txtQuantity.requestFocus();
            return;     //end method
        }
        
        double purchasePrice = 0.0;
        try {
            purchasePrice = Double.parseDouble(txtPurchasePrice.getText());
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Invalid input for Purchase Price. Please use numbers only.", "Error. Invalid Data.", JOptionPane.ERROR_MESSAGE);
            txtPurchasePrice.requestFocus();
            return;     //end method
        }
        
        double currentPrice = 0.0;
        try {
            currentPrice = Double.parseDouble(txtCurrentPrice.getText());
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Invalid input for Current Price. Please use numbers only.", "Error. Invalid Data.", JOptionPane.ERROR_MESSAGE);
            txtCurrentPrice.requestFocus();
            return;     //end method
        }
        
        //create the stock
        Stock stk = new Stock(stockName, quantity, purchasePrice, currentPrice);
        
        //add the Stock object to the JList's model
        model.addElement(stk);
        
        //clear form for the next stock
        txtStockName.setText("");
        txtQuantity.setText("");
        txtPurchasePrice.setText("");
        txtCurrentPrice.setText("");
        
        //put the insertion point on the first field (Stock Name)
        txtStockName.requestFocus();
    }//GEN-LAST:event_btnAddStockActionPerformed

    private void lstStocksValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstStocksValueChanged
        // get stock and show current profir/loss
        Stock stk = lstStocks.getSelectedValue();
        
        if (stk != null) {
            double profitLoss = stk.getProfitLoss();
            DecimalFormat fmt = new DecimalFormat("#,##0.00");
            
            if (profitLoss > 0.0)
                lblProfitLoss.setText("Profit of " + fmt.format(profitLoss));
            else if (profitLoss < 0.0)
                lblProfitLoss.setText("Loss of " + fmt.format(profitLoss));
            else
                lblProfitLoss.setText("Break-even with zero profit/loss");
        }
    }//GEN-LAST:event_lstStocksValueChanged

    private void btnRemoveStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStockActionPerformed
        // get stock position
        int position = lstStocks.getSelectedIndex();
        
        //if selected, remove stock
        if (position >= 0)
        {
            model.remove(position);
            lblProfitLoss.setText("Profit / Loss");
        }
    }//GEN-LAST:event_btnRemoveStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stocks4UsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stocks4UsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stocks4UsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stocks4UsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Stocks4UsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStock;
    private javax.swing.JButton btnRemoveStock;
    private javax.swing.JTabbedPane jtpMainTabs;
    private javax.swing.JLabel lblCurrentPrice;
    private javax.swing.JLabel lblProfitLoss;
    private javax.swing.JLabel lblPurchasePrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblStockName;
    private javax.swing.JList<Stock> lstStocks;
    private javax.swing.JPanel pnlAddStock;
    private javax.swing.JPanel pnlStockList;
    private javax.swing.JScrollPane scrStocks;
    private javax.swing.JTextField txtCurrentPrice;
    private javax.swing.JTextField txtPurchasePrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtStockName;
    // End of variables declaration//GEN-END:variables
}
